---
apiVersion: mariadb.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: example-mariadb
  namespace: example-mariadb
spec:
  masters: 1
  replicas: 0
  mariadb_password: gar
  mariadb_image: mariadb:10.4
  mariadb_pvc_storage_request: 100Mi
