- name: Instalar HaProxy
  hosts: balanceador
  become: true

  tasks:
    - name: Instalar Haproxy
      apt:
        name: haproxy
        state: present

    - name: Copiar archivo de configuracion HaProxy
      copy:
        src: ./haproxy/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
    
    - name: Reiniciar servicio HAProxy
      systemd:
        name: haproxy
        state: restarted

    - name: Permitir tráfico saliente
      command: iptables -P OUTPUT ACCEPT
      ignore_errors: true

    - name: Permitir tráfico de reenvío
      command: iptables -P FORWARD ACCEPT
      ignore_errors: true
      
    - name: Permitir tráfico entrante por el puerto SSH proveniente del nodo0
      command: iptables -A INPUT -s 192.168.1.140 -p tcp --dport 22 -j ACCEPT
      ignore_errors: true

    - name: Aceptar tráfico entrante a los puertos 443 y 80
      command: iptables -A INPUT -p tcp --dport 443 -j ACCEPT
      ignore_errors: true

      command: iptables -A INPUT -p tcp --dport 80 -j ACCEPT
      ignore_errors: true
      
    - name: Permitir el tráfico entrante relacionado y establecido
      command: sudo iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      ignore_errors: true
      
    - name: Denegar tráfico entrante
      command: iptables -P INPUT ACCEPT
      ignore_errors: true