---
- name: "Installing Required Packages"
  apt:
    name:
    - "docker.io"
    - "iproute2"
    - "apt-transport-https"
    - "curl"
    update_cache: yes
    state: present

- name: "Adding Kubernetes APT Key"
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present

- name: "Adding Kubernetes APT Repository"
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present

- name: "Installing Kubeadm, Kubelet, and Kubectl"
  apt:
    name: [ 'kubelet', 'kubeadm', 'kubectl' ]
    state: present
    update_cache: yes

- name: Ensure br_netfilter is enabled.
  modprobe:
    name: br_netfilter
    state: present

- name: update kernel settings
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: "Copy Daemon file to change the Docker's cgroup Driver"
  copy:
    src: daemon.json
    dest: "/etc/docker/daemon.json"

- name: "Starting Docker Service"
  service:
    name: "docker"
    state: started
    enabled: yes

- name: "Starting Kubelet Service"
  service:
    name: "kubelet"
    state: started
    enabled: yes

- name: "Copying token to slave nodes"
  copy: 
    src: /tmp/token
    dest: /tmp/token

- name: "Joining the cluster"
  shell: "bash /tmp/token"
  ignore_errors: True
