- name: Instalar HaProxy
  hosts: balanceador
  become: true

  tasks:
    - name: Instalar Haproxy
      apt:
        name: haproxy
        state: present

    - name: Copiar archivo de configuracion HaProxy
      copy:
        src: /haproxy/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg