- name: Instalar Apache2 y PHP
  hosts: http
  become: true

  tasks:
    - name: Instalar Apache2
      apt:
        name: apache2
        state: present

    - name: Instalar PHP y módulos
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - php
        - libapache2-mod-php
        - php-mysql
        - php-curl
        - php-gd
        - php-xml
        - php-mbstring
        - php-xmlrpc
        - php-zip
        - php-soap
        - php-intl


    - name: Copiar archivo MediaWiki
      copy:
        src: ./mediawiki/mediawiki-1.40.0.tar.gz
        dest: /var/www/html/mediawiki-1.40.0.tar

    - name: Extraer archivo MediaWiki
      command: tar xvf /var/www/html/mediawiki-1.40.0.tar
      args:
        chdir: /var/www/html/
        
    - name: Permitir tráfico saliente pero no de reenvío ni de entrada
      command: iptables -P OUTPUT ACCEPT
      ignore_errors: true

    - name: Denegar tráfico de reenvío
      command: iptables -P FORWARD DROP
      ignore_errors: true

    - name: Permitir tráfico entrante por el puerto SSH proveniente del nodo0
      command: iptables -A INPUT -s 192.168.1.140 -p tcp --dport 22 -j ACCEPT
      ignore_errors: true

    - name: Aceptar tráfico entrante al puerto 443 desde el balanceador
      command: iptables -A INPUT -p tcp -s 192.168.1.150 --dport 443 -j ACCEPT
      ignore_errors: true

    - name: Aceptar tráfico entrante al puerto 80 desde el balanceador
      command: iptables -A INPUT -p tcp -s 192.168.1.150 --dport 80 -j ACCEPT
      ignore_errors: true

    - name: Permitir tráfico entrante relacionado y establecido
      command: iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      ignore_errors: true